[2024-01-03T07:17:06.001+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 24_01_02_fx_mkt_data.first_attempt manual__2024-01-03T07:17:01.075400+00:00 [queued]>
[2024-01-03T07:17:06.037+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 24_01_02_fx_mkt_data.first_attempt manual__2024-01-03T07:17:01.075400+00:00 [queued]>
[2024-01-03T07:17:06.038+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2024-01-03T07:17:06.088+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): first_attempt> on 2024-01-03 07:17:01.075400+00:00
[2024-01-03T07:17:06.105+0000] {standard_task_runner.py:57} INFO - Started process 1012 to run task
[2024-01-03T07:17:06.115+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', '24_01_02_fx_mkt_data', 'first_attempt', 'manual__2024-01-03T07:17:01.075400+00:00', '--job-id', '281', '--raw', '--subdir', 'DAGS_FOLDER/get_fx_mkt_data.py', '--cfg-path', '/tmp/tmp4lu3mlzs']
[2024-01-03T07:17:06.122+0000] {standard_task_runner.py:85} INFO - Job 281: Subtask first_attempt
[2024-01-03T07:17:06.352+0000] {task_command.py:416} INFO - Running <TaskInstance: 24_01_02_fx_mkt_data.first_attempt manual__2024-01-03T07:17:01.075400+00:00 [running]> on host ff92cbb9a252
[2024-01-03T07:17:06.764+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='24_01_02_fx_mkt_data' AIRFLOW_CTX_TASK_ID='first_attempt' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T07:17:01.075400+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-03T07:17:01.075400+00:00'
[2024-01-03T07:17:06.768+0000] {oandapyV20.py:207} INFO - setting up API-client for environment practice
[2024-01-03T07:17:08.244+0000] {logging_mixin.py:154} INFO - vendor id: 6
[2024-01-03T07:17:08.271+0000] {logging_mixin.py:154} INFO - security id: 46686, symbol: AUD_USD, last date: None
[2024-01-03T07:17:08.276+0000] {oandapyV20.py:261} INFO - performing request https://api-fxpractice.oanda.com/v3/instruments/AUD_USD/candles
[2024-01-03T07:17:08.756+0000] {oandapyV20.py:261} INFO - performing request https://api-fxpractice.oanda.com/v3/instruments/AUD_USD/candles
[2024-01-03T07:17:26.751+0000] {logging_mixin.py:154} INFO - Error processing AUD_USD: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "security_daily_price_pkey"
DETAIL:  Key (security_id, date)=(46686, 2017-11-02 21:00:00) already exists.

[SQL: INSERT INTO security_daily_price (security_id, created, updated, date, volume) VALUES (%(security_id)s, %(created)s, %(updated)s, %(date)s, %(volume)s)]
[parameters: ({'security_id': 46686, 'created': datetime.datetime(2024, 1, 3, 7, 17, 2, 37623), 'updated': datetime.datetime(2024, 1, 3, 7, 17, 2, 37776), 'date': Timestamp('2010-12-29 22:00:00+0000', tz='UTC'), 'volume': 14112}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 3, 7, 17, 2, 37623), 'updated': datetime.datetime(2024, 1, 3, 7, 17, 2, 37776), 'date': Timestamp('2010-12-30 22:00:00+0000', tz='UTC'), 'volume': 11245}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 3, 7, 17, 2, 37623), 'updated': datetime.datetime(2024, 1, 3, 7, 17, 2, 37776), 'date': Timestamp('2011-01-01 22:00:00+0000', tz='UTC'), 'volume': 434}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 3, 7, 17, 2, 37623), 'updated': datetime.datetime(2024, 1, 3, 7, 17, 2, 37776), 'date': Timestamp('2011-01-02 22:00:00+0000', tz='UTC'), 'volume': 9509}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 3, 7, 17, 2, 37623), 'updated': datetime.datetime(2024, 1, 3, 7, 17, 2, 37776), 'date': Timestamp('2011-01-03 22:00:00+0000', tz='UTC'), 'volume': 19899}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 3, 7, 17, 2, 37623), 'updated': datetime.datetime(2024, 1, 3, 7, 17, 2, 37776), 'date': Timestamp('2011-01-04 22:00:00+0000', tz='UTC'), 'volume': 22346}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 3, 7, 17, 2, 37623), 'updated': datetime.datetime(2024, 1, 3, 7, 17, 2, 37776), 'date': Timestamp('2011-01-05 22:00:00+0000', tz='UTC'), 'volume': 17923}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 3, 7, 17, 2, 37623), 'updated': datetime.datetime(2024, 1, 3, 7, 17, 2, 37776), 'date': Timestamp('2011-01-06 22:00:00+0000', tz='UTC'), 'volume': 20265}  ... displaying 10 of 3571 total bound parameter sets ...  {'security_id': 46686, 'created': datetime.datetime(2024, 1, 3, 7, 17, 2, 37623), 'updated': datetime.datetime(2024, 1, 3, 7, 17, 2, 37776), 'date': Timestamp('2024-01-01 22:00:00+0000', tz='UTC'), 'volume': 51124}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 3, 7, 17, 2, 37623), 'updated': datetime.datetime(2024, 1, 3, 7, 17, 2, 37776), 'date': Timestamp('2024-01-02 22:00:00+0000', tz='UTC'), 'volume': 13462})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2024-01-03T07:17:26.752+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-03T07:17:26.814+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=24_01_02_fx_mkt_data, task_id=first_attempt, execution_date=20240103T071701, start_date=20240103T071706, end_date=20240103T071726
[2024-01-03T07:17:26.930+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-03T07:17:27.028+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
