[2024-01-02T19:03:05.343+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 24_01_02_fx_mkt_data.first_attempt manual__2024-01-02T19:03:00.564400+00:00 [queued]>
[2024-01-02T19:03:05.374+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 24_01_02_fx_mkt_data.first_attempt manual__2024-01-02T19:03:00.564400+00:00 [queued]>
[2024-01-02T19:03:05.375+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2024-01-02T19:03:05.427+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): first_attempt> on 2024-01-02 19:03:00.564400+00:00
[2024-01-02T19:03:05.444+0000] {standard_task_runner.py:57} INFO - Started process 2827 to run task
[2024-01-02T19:03:05.454+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', '24_01_02_fx_mkt_data', 'first_attempt', 'manual__2024-01-02T19:03:00.564400+00:00', '--job-id', '217', '--raw', '--subdir', 'DAGS_FOLDER/get_fx_mkt_data.py', '--cfg-path', '/tmp/tmpf3qh66_1']
[2024-01-02T19:03:05.461+0000] {standard_task_runner.py:85} INFO - Job 217: Subtask first_attempt
[2024-01-02T19:03:05.690+0000] {task_command.py:416} INFO - Running <TaskInstance: 24_01_02_fx_mkt_data.first_attempt manual__2024-01-02T19:03:00.564400+00:00 [running]> on host ff92cbb9a252
[2024-01-02T19:03:06.098+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='24_01_02_fx_mkt_data' AIRFLOW_CTX_TASK_ID='first_attempt' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T19:03:00.564400+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-02T19:03:00.564400+00:00'
[2024-01-02T19:03:06.102+0000] {oandapyV20.py:207} INFO - setting up API-client for environment practice
[2024-01-02T19:03:07.231+0000] {oandapyV20.py:261} INFO - performing request https://api-fxpractice.oanda.com/v3/instruments/AUD_USD/candles
[2024-01-02T19:03:08.008+0000] {oandapyV20.py:261} INFO - performing request https://api-fxpractice.oanda.com/v3/instruments/AUD_USD/candles
[2024-01-02T19:03:11.044+0000] {logging_mixin.py:154} INFO - 3570
[2024-01-02T19:03:11.626+0000] {warnings.py:109} WARNING - /opt/airflow/app/repository/entity.py:52: SAWarning: Column 'security_daily_price.security_id' is marked as a member of the primary key for table 'security_daily_price', but has no Python-side or server-side default generator indicated, nor does it indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.  Primary key columns typically may not store NULL. Note that as of SQLAlchemy 1.1, 'autoincrement=True' must be indicated explicitly for composite (e.g. multicolumn) primary keys if AUTO_INCREMENT/SERIAL/IDENTITY behavior is expected for one of the columns in the primary key. CREATE TABLE statements are impacted by this change as well on most backends.
  self.session.bulk_insert_mappings(self.entity, records)

[2024-01-02T19:03:11.831+0000] {logging_mixin.py:154} INFO - Error processing AUD_USD: (psycopg2.errors.NotNullViolation) null value in column "security_id" of relation "security_daily_price" violates not-null constraint
DETAIL:  Failing row contains (null, null, 2024-01-02 19:03:01.710016, 2024-01-02 19:03:01.710141, 2010-12-29 22:00:00, null, null, null, null, 14112).

[SQL: INSERT INTO security_daily_price (created, updated, date, volume) VALUES (%(created)s, %(updated)s, %(date)s, %(volume)s)]
[parameters: ({'created': datetime.datetime(2024, 1, 2, 19, 3, 1, 710016), 'updated': datetime.datetime(2024, 1, 2, 19, 3, 1, 710141), 'date': Timestamp('2010-12-29 22:00:00+0000', tz='UTC'), 'volume': 14112}, {'created': datetime.datetime(2024, 1, 2, 19, 3, 1, 710016), 'updated': datetime.datetime(2024, 1, 2, 19, 3, 1, 710141), 'date': Timestamp('2010-12-30 22:00:00+0000', tz='UTC'), 'volume': 11245}, {'created': datetime.datetime(2024, 1, 2, 19, 3, 1, 710016), 'updated': datetime.datetime(2024, 1, 2, 19, 3, 1, 710141), 'date': Timestamp('2011-01-01 22:00:00+0000', tz='UTC'), 'volume': 434}, {'created': datetime.datetime(2024, 1, 2, 19, 3, 1, 710016), 'updated': datetime.datetime(2024, 1, 2, 19, 3, 1, 710141), 'date': Timestamp('2011-01-02 22:00:00+0000', tz='UTC'), 'volume': 9509}, {'created': datetime.datetime(2024, 1, 2, 19, 3, 1, 710016), 'updated': datetime.datetime(2024, 1, 2, 19, 3, 1, 710141), 'date': Timestamp('2011-01-03 22:00:00+0000', tz='UTC'), 'volume': 19899}, {'created': datetime.datetime(2024, 1, 2, 19, 3, 1, 710016), 'updated': datetime.datetime(2024, 1, 2, 19, 3, 1, 710141), 'date': Timestamp('2011-01-04 22:00:00+0000', tz='UTC'), 'volume': 22346}, {'created': datetime.datetime(2024, 1, 2, 19, 3, 1, 710016), 'updated': datetime.datetime(2024, 1, 2, 19, 3, 1, 710141), 'date': Timestamp('2011-01-05 22:00:00+0000', tz='UTC'), 'volume': 17923}, {'created': datetime.datetime(2024, 1, 2, 19, 3, 1, 710016), 'updated': datetime.datetime(2024, 1, 2, 19, 3, 1, 710141), 'date': Timestamp('2011-01-06 22:00:00+0000', tz='UTC'), 'volume': 20265}  ... displaying 10 of 3570 total bound parameter sets ...  {'created': datetime.datetime(2024, 1, 2, 19, 3, 1, 710016), 'updated': datetime.datetime(2024, 1, 2, 19, 3, 1, 710141), 'date': Timestamp('2023-12-28 22:00:00+0000', tz='UTC'), 'volume': 41818}, {'created': datetime.datetime(2024, 1, 2, 19, 3, 1, 710016), 'updated': datetime.datetime(2024, 1, 2, 19, 3, 1, 710141), 'date': Timestamp('2024-01-01 22:00:00+0000', tz='UTC'), 'volume': 47777})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2024-01-02T19:03:11.832+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-02T19:03:11.906+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=24_01_02_fx_mkt_data, task_id=first_attempt, execution_date=20240102T190300, start_date=20240102T190305, end_date=20240102T190311
[2024-01-02T19:03:12.009+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-02T19:03:12.099+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
