[2024-01-02T19:29:50.692+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 24_01_02_fx_mkt_data.first_attempt manual__2024-01-02T19:29:46.240062+00:00 [queued]>
[2024-01-02T19:29:50.725+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 24_01_02_fx_mkt_data.first_attempt manual__2024-01-02T19:29:46.240062+00:00 [queued]>
[2024-01-02T19:29:50.726+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2024-01-02T19:29:50.778+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): first_attempt> on 2024-01-02 19:29:46.240062+00:00
[2024-01-02T19:29:50.796+0000] {standard_task_runner.py:57} INFO - Started process 3189 to run task
[2024-01-02T19:29:50.807+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', '24_01_02_fx_mkt_data', 'first_attempt', 'manual__2024-01-02T19:29:46.240062+00:00', '--job-id', '227', '--raw', '--subdir', 'DAGS_FOLDER/get_fx_mkt_data.py', '--cfg-path', '/tmp/tmpb34mojia']
[2024-01-02T19:29:50.814+0000] {standard_task_runner.py:85} INFO - Job 227: Subtask first_attempt
[2024-01-02T19:29:51.055+0000] {task_command.py:416} INFO - Running <TaskInstance: 24_01_02_fx_mkt_data.first_attempt manual__2024-01-02T19:29:46.240062+00:00 [running]> on host ff92cbb9a252
[2024-01-02T19:29:51.499+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='24_01_02_fx_mkt_data' AIRFLOW_CTX_TASK_ID='first_attempt' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T19:29:46.240062+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-02T19:29:46.240062+00:00'
[2024-01-02T19:29:51.503+0000] {oandapyV20.py:207} INFO - setting up API-client for environment practice
[2024-01-02T19:29:53.753+0000] {logging_mixin.py:154} INFO - vendor id: 6
[2024-01-02T19:29:53.791+0000] {logging_mixin.py:154} INFO - security id: 46686, symbol: AUD_USD, last date: None
[2024-01-02T19:29:53.796+0000] {oandapyV20.py:261} INFO - performing request https://api-fxpractice.oanda.com/v3/instruments/AUD_USD/candles
[2024-01-02T19:29:54.349+0000] {oandapyV20.py:261} INFO - performing request https://api-fxpractice.oanda.com/v3/instruments/AUD_USD/candles
[2024-01-02T19:29:57.389+0000] {logging_mixin.py:154} INFO - 3570
[2024-01-02T19:29:58.480+0000] {logging_mixin.py:154} INFO - Error processing AUD_USD: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "security_daily_price_pkey"
DETAIL:  Key (security_id, date)=(46686, 2017-11-02 21:00:00) already exists.

[SQL: INSERT INTO security_daily_price (security_id, created, updated, date, volume) VALUES (%(security_id)s, %(created)s, %(updated)s, %(date)s, %(volume)s)]
[parameters: ({'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 29, 47, 8723), 'updated': datetime.datetime(2024, 1, 2, 19, 29, 47, 8869), 'date': Timestamp('2010-12-29 22:00:00+0000', tz='UTC'), 'volume': 14112}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 29, 47, 8723), 'updated': datetime.datetime(2024, 1, 2, 19, 29, 47, 8869), 'date': Timestamp('2010-12-30 22:00:00+0000', tz='UTC'), 'volume': 11245}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 29, 47, 8723), 'updated': datetime.datetime(2024, 1, 2, 19, 29, 47, 8869), 'date': Timestamp('2011-01-01 22:00:00+0000', tz='UTC'), 'volume': 434}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 29, 47, 8723), 'updated': datetime.datetime(2024, 1, 2, 19, 29, 47, 8869), 'date': Timestamp('2011-01-02 22:00:00+0000', tz='UTC'), 'volume': 9509}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 29, 47, 8723), 'updated': datetime.datetime(2024, 1, 2, 19, 29, 47, 8869), 'date': Timestamp('2011-01-03 22:00:00+0000', tz='UTC'), 'volume': 19899}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 29, 47, 8723), 'updated': datetime.datetime(2024, 1, 2, 19, 29, 47, 8869), 'date': Timestamp('2011-01-04 22:00:00+0000', tz='UTC'), 'volume': 22346}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 29, 47, 8723), 'updated': datetime.datetime(2024, 1, 2, 19, 29, 47, 8869), 'date': Timestamp('2011-01-05 22:00:00+0000', tz='UTC'), 'volume': 17923}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 29, 47, 8723), 'updated': datetime.datetime(2024, 1, 2, 19, 29, 47, 8869), 'date': Timestamp('2011-01-06 22:00:00+0000', tz='UTC'), 'volume': 20265}  ... displaying 10 of 3570 total bound parameter sets ...  {'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 29, 47, 8723), 'updated': datetime.datetime(2024, 1, 2, 19, 29, 47, 8869), 'date': Timestamp('2023-12-28 22:00:00+0000', tz='UTC'), 'volume': 41818}, {'security_id': 46686, 'created': datetime.datetime(2024, 1, 2, 19, 29, 47, 8723), 'updated': datetime.datetime(2024, 1, 2, 19, 29, 47, 8869), 'date': Timestamp('2024-01-01 22:00:00+0000', tz='UTC'), 'volume': 48389})]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2024-01-02T19:29:58.481+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-01-02T19:29:58.544+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=24_01_02_fx_mkt_data, task_id=first_attempt, execution_date=20240102T192946, start_date=20240102T192950, end_date=20240102T192958
[2024-01-02T19:29:58.642+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-02T19:29:58.736+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
